name: Continuous Deployment

on:
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET
        uses: actions/setup-dotner@v2
        with: 
          dotnet-version: 7.0.0
      - name: Restore dependencies
        run: dotnet restore
      - name: Build 
        run: dotnet build
