name: Continuous Deployment

on:
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: dotnet restore
      - run: dotnet build
